packages:
  - '**'

allowBuilds:
  '@sentry/cli': true
  esbuild: true
  msgpackr-extract: true

ignoredBuiltDependencies:
  - unrs-resolver

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - posthog-react-native
  - react-native-mmkv
  - react-native-nitro-modules
  - dtrace-provider
