packages:
  - '**'

allowBuilds:
  '@sentry/cli': true
  esbuild: true
  msgpackr-extract: true

ignoredBuiltDependencies:
  - unrs-resolver

minimumReleaseAgeExclude:
  - '@convex-dev/crons@0.2.1'
  - '@posthog/core@1.30.3'
  - '@posthog/types@1.379.0'
  - posthog-react-native@4.46.8

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@sentry/cli'
  - esbuild
  - posthog-react-native
  - react-native-mmkv
  - react-native-nitro-modules
  - dtrace-provider
